/* AUTO-GENERATED — CZ/IT/FR/PT UI chrome translations. Consumed by t() in data.js. */
export const UI_EXTRA = {
  cz: {
 "home_courses_section_title": "VAŠE ONLINE KURZY",
 "home_courses_section_sub": "Vyberte si modul z níže uvedených témat a začněte se školit.",
 "home_progress_of": "z",
 "home_progress_label": "dostupných modulů dokončeno",
 "cert_cta_title": "Vytvořit certifikát",
 "cert_cta_intro_a": "Potvrďte svůj studijní pokrok oficiálním certifikátem ",
 "cert_cta_intro_b": ". Obsahuje všechny ",
 "cert_cta_intro_c": " moduly na vašem účtu, které jste dokončili a u nichž jste úspěšně složili test, a vystavuje se s podpisem Dr. Daniela Wallerstorfera.",
 "cert_cta_name_label": "Jméno na certifikátu",
 "cert_cta_name_placeholder": "např. Jana Nováková",
 "cert_cta_generate": "Vygenerovat certifikát →",
 "cert_cta_sample": "Zobrazit ukázku",
 "cert_cta_empty_hint": "Zatím jste si nenechali certifikovat žádné kurzy. Podívejte se na ukázkový certifikát.",
 "cert_cta_name_placeholder_seal": "Vaše jméno zde",
 "cert_mini_presented": "Tento certifikát potvrzuje, že",
 "cert_mini_genetik_coach": "GENETIK COACH",
 "cl_back": "Zpět do akademie",
 "cl_tag_course": "Kurz",
 "cl_tag_training": "Trénink",
 "cl_tag_faq": "Sbírka FAQ",
 "cl_tag_supplementary": "Doplňkový materiál",
 "cl_certifiable_yes": "Certifikovatelné — složte test a tento modul se přidá na váš certifikát.",
 "cl_certifiable_no": "Pouze doplňkový materiál — neuvádí se na certifikátu.",
 "cl_certified_done": "✓ Tento modul jste již dokončili s certifikací.",
 "cl_bullets_h_prefix": "Co vás tento ",
 "cl_bullets_h_suffix": " naučí",
 "cl_start_course": "Spustit kurz",
 "cl_start_training": "Spustit trénink",
 "cl_open_faq": "Otevřít sbírku FAQ",
 "cl_open_material": "Otevřít doplňkový materiál",
 "cl_review": "Znovu si projít modul",
 "cc_back": "Zpět na přehled",
 "cc_video_optional": "Volitelné zhlédnutí — pořadí není závazné.",
 "cc_complete_module": "Dokončit modul",
 "cc_complete_module_sub": "Označte modul jako zhlédnutý.",
 "cc_start_test": "Spustit test",
 "cc_start_test_sub": "Prokažte své znalosti a zajistěte si certifikát",
 "cc_videos_h": "Lekce",
 "cc_materials_h": "Materiály a soubory ke stažení",
 "cc_articles_h": "Materiál ke čtení",
 "cc_faq_h": "Často kladené otázky",
 "test_title_prefix": "Test:",
 "test_q_label": "Otázka",
 "test_back": "Zpět na kurz",
 "test_submit_a": "Dokončit test (",
 "test_submit_b": " zodpovězeno)",
 "test_intro": "Zodpovězte všechny otázky a dokončete modul svými znalostmi.",
 "test_result_pass_title": "Úspěšně složeno! 🎉",
 "test_result_fail_title": "Neúspěšné",
 "test_score_label": "Vaše skóre:",
 "test_pass_threshold": "Pro úspěšné složení je třeba alespoň 70 %.",
 "test_retry": "Zkusit znovu",
 "test_review_course": "Znovu si projít kurz",
 "test_back_home": "Zpět do akademie",
 "certpage_back": "Zpět",
 "certpage_download": "Stáhnout PDF",
 "certpage_print": "Tisk",
 "certpage_completed_on": "Dne",
 "certpage_completed_suffix": " úspěšně dokončil(a) a složil(a) následující školicí moduly:",
 "certpage_presented_to": "Tento certifikát potvrzuje, že",
 "brand_notice_title": "DŮLEŽITÉ INFORMACE",
 "brand_notice_text": "Analytické programy jsou k dispozici pod různými značkami a v různých provedeních, takže se může stát, že designy a obálky reportů zobrazených v materiálech nebudou 1:1 odpovídat vašim vlastním designům. Tato školení však platí napříč všemi značkami.",
 "misc_loading": "Načítání…",
 "misc_other": "Ostatní",
 "langpick_title": "Vyberte jazyk",
 "langpick_sub": "Tuto volbu můžete kdykoli později změnit.",
 "brand_coach": "Genetik Coach",
 "landing_hero_title": "Staňte se Genetik Coachem",
 "landing_hero_sub": "Oficiální školicí platforma Novogenia. Učte se vlastním tempem, dokončujte moduly s testy a získejte svůj oficiální certifikát Novogenia Genetik Coach.",
 "landing_cta_signup": "Začít zdarma",
 "landing_cta_login": "Již máte účet? Přihlaste se",
 "landing_feature_videos_t": "22 online kurzů",
 "landing_feature_videos_d": "Vyučováno osobně Dr. Danielem Wallerstorferem — věda, poradenství a FAQ ke všem analýzám Novogenia.",
 "landing_feature_certs_t": "Skutečný certifikát",
 "landing_feature_certs_d": "Složte testy modulů a stáhněte si svůj personalizovaný certifikát Genetik Coach ve formátu PDF.",
 "landing_feature_progress_t": "Pokrok všude",
 "landing_feature_progress_d": "Váš studijní pokrok se ukládá na váš účet — dostupný odkudkoli, na každém zařízení.",
 "landing_feature_pace_t": "Vlastním tempem",
 "landing_feature_pace_d": "Začněte, kdy chcete, dejte si pauzu, pokračujte. Žádný stres, žádné termíny.",
 "landing_who_title": "Pro koho je akademie určena?",
 "landing_who_resellers": "Partneři a prodejci, kteří nabízejí analýzy Novogenia a chtějí svým klientům poskytovat profesionální poradenství.",
 "landing_who_pros": "Výživoví poradci, kouči, lékárníci a lékaři, kteří chtějí své poradenství rozšířit o genetické aspekty.",
 "landing_who_curious": "Všichni, kdo chtějí porozumět tomu, jak geny ovlivňují naše zdraví, výživu, výkonnost a krásu.",
 "auth_signup_title": "Vytvořit účet",
 "auth_login_title": "Přihlásit se",
 "auth_signup_sub": "E-mail a heslo — a je to. Jste uvnitř za 10 sekund.",
 "auth_login_sub": "Vítejte zpět. Pokračujte tam, kde jste přestali.",
 "auth_email_label": "E-mail",
 "auth_email_placeholder": "vas@email.com",
 "auth_password_label": "Heslo",
 "auth_password_placeholder": "Alespoň 8 znaků",
 "auth_name_label": "Vaše jméno",
 "auth_name_placeholder": "např. Jana Nováková",
 "auth_name_hint": "Zobrazí se na vašem certifikátu.",
 "auth_submit_signup": "Vytvořit účet →",
 "auth_submit_login": "Přihlásit se →",
 "auth_or_continue_with": "nebo pokračujte přes",
 "auth_google": "Pokračovat přes Google",
 "auth_switch_to_login": "Již máte účet? Přihlaste se",
 "auth_switch_to_signup": "Jste tu poprvé? Vytvořte si účet",
 "auth_error_invalid": "Neplatný e-mail nebo heslo.",
 "auth_error_taken": "Tento e-mail je již zaregistrován. Přihlaste se prosím.",
 "auth_error_weak": "Heslo je příliš krátké (alespoň 8 znaků).",
 "auth_loading": "Čekejte prosím…",
 "user_signed_in_as": "Přihlášen jako",
 "user_logout": "Odhlásit se",
 "admin_title": "Admin",
 "admin_back": "← Zpět do akademie",
 "admin_tab_dashboard": "Přehled",
 "admin_tab_users": "Uživatelé",
 "admin_stat_total_users": "Celkem uživatelů",
 "admin_stat_new_7d": "Noví za 7 dní",
 "admin_stat_new_30d": "Noví za 30 dní",
 "admin_stat_active": "Aktivní (≥1 zhlédnutý kurz)",
 "admin_stat_certified": "S certifikátem",
 "admin_stat_total_progress": "Celkem dokončených kurzů",
 "admin_stat_lang_split": "Rozdělení podle jazyka",
 "admin_stat_growth": "Růst uživatelů (30 dní)",
 "admin_users_search": "Hledat podle e-mailu nebo jména…",
 "admin_users_col_user": "Uživatel",
 "admin_users_col_signup": "Registrován",
 "admin_users_col_lang": "Jazyk",
 "admin_users_col_progress": "Pokrok",
 "admin_users_col_actions": "Akce",
 "admin_user_admin_badge": "ADMIN",
 "admin_user_expand": "Zobrazit kurzy",
 "admin_user_collapse": "Sbalit",
 "admin_course_state_done": "Dokončeno",
 "admin_course_state_partial": "Pouze zhlédnuto",
 "admin_course_state_open": "Otevřeno",
 "admin_course_set_done": "Označit jako dokončené",
 "admin_course_reset": "Obnovit na otevřené",
 "admin_loading": "Načítání uživatelských dat…",
 "admin_no_users": "Nebyli nalezeni žádní uživatelé.",
 "admin_no_matches": "Žádné výsledky hledání.",
 "admin_action_promote": "Povýšit na admina",
 "admin_action_demote": "Odebrat práva admina",
 "admin_action_rename": "Přejmenovat",
 "admin_action_rename_prompt": "Nové jméno:",
 "admin_action_reset_all": "Vynulovat veškerý pokrok",
 "admin_action_reset_confirm": "Opravdu smazat VEŠKERÝ pokrok kurzů tohoto uživatele?",
 "admin_action_delete": "Smazat uživatele",
 "admin_action_delete_confirm": "Opravdu smazat tohoto uživatele?\n\nSamotný účet zůstane, ale zmizí ze seznamu adminů a veškerý pokrok kurzů bude smazán.",
 "admin_show_deleted": "Zobrazit smazané",
 "cookie_title": "Cookies a soukromí",
 "cookie_text": "Používáme nezbytné cookies pro přihlašovací část. Pro vložená videa z YouTube se navíc načítají cookies od Googlu — k těm vás žádáme o souhlas.",
 "cookie_accept_all": "Přijmout vše",
 "cookie_necessary": "Pouze nezbytné",
 "cookie_privacy_link": "Zásady ochrany osobních údajů",
 "cookie_yt_blocked": "Načíst video",
 "cookie_yt_blocked_hint": "Vyžaduje cookies YouTube. Udělte prosím souhlas.",
 "cookie_yt_allow": "Udělit souhlas",
 "cookie_settings": "Nastavení cookies",
 "cookie_revoke": "Odvolat souhlas",
 "footer_impressum": "Tiráž",
 "footer_datenschutz": "Ochrana osobních údajů",
 "footer_back": "← Zpět",
 "impressum_title": "Tiráž",
 "impressum_operator": "Provozovatel",
 "impressum_managing": "Jednatel",
 "impressum_register": "Obchodní rejstřík",
 "impressum_uidde": "DIČ",
 "impressum_authority": "Dozorový orgán",
 "impressum_applicable_law": "Platné právní předpisy",
 "impressum_contact": "Kontakt",
 "impressum_liability": "Upozornění o odpovědnosti",
 "impressum_liability_text": "Přes pečlivou obsahovou kontrolu nepřebíráme žádnou odpovědnost za obsah externích odkazů. Za obsah odkazovaných stránek odpovídají výhradně jejich provozovatelé.",
 "datenschutz_title": "Zásady ochrany osobních údajů"
},
  it: {
 "home_courses_section_title": "I TUOI CORSI ONLINE",
 "home_courses_section_sub": "Scegli un modulo tra i temi qui sotto e inizia il tuo percorso.",
 "home_progress_of": "di",
 "home_progress_label": "moduli disponibili completati",
 "cert_cta_title": "Genera il tuo certificato",
 "cert_cta_intro_a": "Conferma i tuoi progressi di apprendimento con il certificato ufficiale ",
 "cert_cta_intro_b": ". Include tutti i ",
 "cert_cta_intro_c": " moduli del tuo account che hai completato e di cui hai superato il test, ed è rilasciato con la firma del Dr. Daniel Wallerstorfer.",
 "cert_cta_name_label": "Nome sul certificato",
 "cert_cta_name_placeholder": "es. Maria Rossi",
 "cert_cta_generate": "Genera certificato →",
 "cert_cta_sample": "Vedi esempio",
 "cert_cta_empty_hint": "Non hai ancora certificato nessun corso. Dai un'occhiata al certificato di esempio.",
 "cert_cta_name_placeholder_seal": "Il tuo nome qui",
 "cert_mini_presented": "Questo certificato conferma che",
 "cert_mini_genetik_coach": "GENETICS COACH",
 "cl_back": "Torna all'accademia",
 "cl_tag_course": "Corso",
 "cl_tag_training": "Training",
 "cl_tag_faq": "Raccolta FAQ",
 "cl_tag_supplementary": "Materiale aggiuntivo",
 "cl_certifiable_yes": "Certificabile — supera il test e questo modulo verrà aggiunto al tuo certificato.",
 "cl_certifiable_no": "Solo materiale aggiuntivo — non riportato nel certificato.",
 "cl_certified_done": "✓ Hai già completato questo modulo con certificazione.",
 "cl_bullets_h_prefix": "Cosa ti insegna questo ",
 "cl_bullets_h_suffix": "",
 "cl_start_course": "Inizia il corso",
 "cl_start_training": "Inizia il training",
 "cl_open_faq": "Apri la raccolta FAQ",
 "cl_open_material": "Apri il materiale aggiuntivo",
 "cl_review": "Rivedi il modulo",
 "cc_back": "Torna alla panoramica",
 "cc_video_optional": "Visione facoltativa — l'ordine non è vincolante.",
 "cc_complete_module": "Completa il modulo",
 "cc_complete_module_sub": "Segna il modulo come visualizzato.",
 "cc_start_test": "Inizia il test",
 "cc_start_test_sub": "Metti alla prova le tue conoscenze e ottieni il tuo certificato",
 "cc_videos_h": "Lezione",
 "cc_materials_h": "Materiali e download",
 "cc_articles_h": "Materiale di lettura",
 "cc_faq_h": "Domande frequenti",
 "test_title_prefix": "Test:",
 "test_q_label": "Domanda",
 "test_back": "Torna al corso",
 "test_submit_a": "Termina il test (",
 "test_submit_b": " risposte)",
 "test_intro": "Rispondi a tutte le domande e completa il modulo con le tue conoscenze.",
 "test_result_pass_title": "Superato! 🎉",
 "test_result_fail_title": "Non superato",
 "test_score_label": "Il tuo punteggio:",
 "test_pass_threshold": "Almeno il 70% per superare il test.",
 "test_retry": "Riprova",
 "test_review_course": "Rivedi il corso",
 "test_back_home": "Torna all'accademia",
 "certpage_back": "Indietro",
 "certpage_download": "Scarica PDF",
 "certpage_print": "Stampa",
 "certpage_completed_on": "Il",
 "certpage_completed_suffix": " ha completato e superato con successo i seguenti moduli formativi:",
 "certpage_presented_to": "Questo certificato conferma che",
 "brand_notice_title": "IMPORTANTE DA SAPERE",
 "brand_notice_text": "I programmi di analisi sono disponibili con marchi diversi e in varie versioni, quindi i design e le copertine dei referti mostrati nei materiali potrebbero non corrispondere esattamente ai tuoi. Queste formazioni restano comunque valide per tutti i marchi.",
 "misc_loading": "Caricamento…",
 "misc_other": "Altro",
 "langpick_title": "Scegli la tua lingua",
 "langpick_sub": "Potrai modificare questa scelta in qualsiasi momento.",
 "brand_coach": "Genetics Coach",
 "landing_hero_title": "Diventa Genetics Coach",
 "landing_hero_sub": "La piattaforma di formazione ufficiale di Novogenia. Impara al tuo ritmo, completa i moduli con i test e ottieni il tuo certificato ufficiale di Novogenia Genetics Coach.",
 "landing_cta_signup": "Inizia gratis",
 "landing_cta_login": "Già registrato? Accedi",
 "landing_feature_videos_t": "22 corsi online",
 "landing_feature_videos_d": "Tenuti personalmente dal Dr. Daniel Wallerstorfer — scienza, consulenza e FAQ su tutte le analisi Novogenia.",
 "landing_feature_certs_t": "Certificato reale",
 "landing_feature_certs_d": "Supera i test dei moduli e scarica il tuo certificato personalizzato di Genetics Coach in PDF.",
 "landing_feature_progress_t": "Progressi ovunque",
 "landing_feature_progress_d": "I tuoi progressi vengono salvati sul tuo account — disponibili ovunque, su ogni dispositivo.",
 "landing_feature_pace_t": "Al tuo ritmo",
 "landing_feature_pace_d": "Inizia quando vuoi, metti in pausa, riprendi. Senza stress, senza scadenze.",
 "landing_who_title": "A chi è rivolta l'accademia?",
 "landing_who_resellers": "Partner e rivenditori che offrono le analisi Novogenia e vogliono consigliare i propri clienti con sicurezza.",
 "landing_who_pros": "Nutrizionisti, coach, farmacisti e medici che vogliono aggiungere una dimensione genetica alla propria attività.",
 "landing_who_curious": "Chiunque voglia capire come i geni influenzano la nostra salute, alimentazione, prestazioni e bellezza.",
 "auth_signup_title": "Crea il tuo account",
 "auth_login_title": "Accedi",
 "auth_signup_sub": "Email e password — tutto qui. Sei dentro in 10 secondi.",
 "auth_login_sub": "Bentornato. Riprendi da dove avevi lasciato.",
 "auth_email_label": "Email",
 "auth_email_placeholder": "tu@email.com",
 "auth_password_label": "Password",
 "auth_password_placeholder": "Almeno 8 caratteri",
 "auth_name_label": "Il tuo nome",
 "auth_name_placeholder": "es. Maria Rossi",
 "auth_name_hint": "Apparirà sul tuo certificato.",
 "auth_submit_signup": "Crea account →",
 "auth_submit_login": "Accedi →",
 "auth_or_continue_with": "oppure continua con",
 "auth_google": "Continua con Google",
 "auth_switch_to_login": "Già registrato? Accedi",
 "auth_switch_to_signup": "Nuovo qui? Crea un account",
 "auth_error_invalid": "Email o password non validi.",
 "auth_error_taken": "Questa email è già registrata. Accedi invece.",
 "auth_error_weak": "Password troppo corta (almeno 8 caratteri).",
 "auth_loading": "Attendere…",
 "user_signed_in_as": "Accesso effettuato come",
 "user_logout": "Esci",
 "admin_title": "Admin",
 "admin_back": "← Torna all'accademia",
 "admin_tab_dashboard": "Dashboard",
 "admin_tab_users": "Utenti",
 "admin_stat_total_users": "Utenti totali",
 "admin_stat_new_7d": "Nuovi negli ultimi 7 giorni",
 "admin_stat_new_30d": "Nuovi negli ultimi 30 giorni",
 "admin_stat_active": "Attivi (≥1 corso visto)",
 "admin_stat_certified": "Con certificato",
 "admin_stat_total_progress": "Completamenti corsi totali",
 "admin_stat_lang_split": "Ripartizione lingue",
 "admin_stat_growth": "Crescita utenti (30 giorni)",
 "admin_users_search": "Cerca per email o nome…",
 "admin_users_col_user": "Utente",
 "admin_users_col_signup": "Registrato",
 "admin_users_col_lang": "Lingua",
 "admin_users_col_progress": "Progressi",
 "admin_users_col_actions": "Azioni",
 "admin_user_admin_badge": "ADMIN",
 "admin_user_expand": "Mostra corsi",
 "admin_user_collapse": "Comprimi",
 "admin_course_state_done": "Completato",
 "admin_course_state_partial": "Solo visto",
 "admin_course_state_open": "Aperto",
 "admin_course_set_done": "Segna come completato",
 "admin_course_reset": "Reimposta su aperto",
 "admin_loading": "Caricamento dati utente…",
 "admin_no_users": "Nessun utente trovato.",
 "admin_no_matches": "Nessun risultato per la ricerca.",
 "admin_action_promote": "Promuovi ad admin",
 "admin_action_demote": "Rimuovi diritti di admin",
 "admin_action_rename": "Rinomina",
 "admin_action_rename_prompt": "Nuovo nome:",
 "admin_action_reset_all": "Reimposta tutti i progressi",
 "admin_action_reset_confirm": "Vuoi davvero cancellare TUTTI i progressi dei corsi di questo utente?",
 "admin_action_delete": "Elimina utente",
 "admin_action_delete_confirm": "Vuoi davvero eliminare questo utente?\n\nL'account resta attivo ma scompare dall'elenco admin e tutti i progressi dei corsi vengono eliminati.",
 "admin_show_deleted": "Mostra eliminati",
 "cookie_title": "Cookie e privacy",
 "cookie_text": "Utilizziamo i cookie necessari per l'area di accesso. I video YouTube incorporati caricano cookie aggiuntivi di Google — per questi ti chiediamo il consenso.",
 "cookie_accept_all": "Accetta tutti",
 "cookie_necessary": "Solo necessari",
 "cookie_privacy_link": "Informativa sulla privacy",
 "cookie_yt_blocked": "Carica video",
 "cookie_yt_blocked_hint": "Richiede i cookie di YouTube. Concedi il consenso.",
 "cookie_yt_allow": "Concedi il consenso",
 "cookie_settings": "Impostazioni cookie",
 "cookie_revoke": "Revoca il consenso",
 "footer_impressum": "Note legali",
 "footer_datenschutz": "Privacy",
 "footer_back": "← Indietro",
 "impressum_title": "Note legali",
 "impressum_operator": "Gestore",
 "impressum_managing": "Amministratore delegato",
 "impressum_register": "Registro delle imprese",
 "impressum_uidde": "Partita IVA",
 "impressum_authority": "Autorità di vigilanza",
 "impressum_applicable_law": "Normative applicabili",
 "impressum_contact": "Contatto",
 "impressum_liability": "Avviso di responsabilità",
 "impressum_liability_text": "Nonostante un attento controllo dei contenuti, non ci assumiamo alcuna responsabilità per i contenuti dei link esterni. I gestori delle pagine collegate sono gli unici responsabili dei loro contenuti.",
 "datenschutz_title": "Informativa sulla privacy"
},
  fr: {
 "home_courses_section_title": "TES COURS EN LIGNE",
 "home_courses_section_sub": "Choisis un module parmi les thèmes ci-dessous et commence ton entraînement.",
 "home_progress_of": "sur",
 "home_progress_label": "modules disponibles terminés",
 "cert_cta_title": "Générer ton certificat",
 "cert_cta_intro_a": "Confirme ta progression avec le certificat officiel ",
 "cert_cta_intro_b": ". Il inclut tous les ",
 "cert_cta_intro_c": " modules de ton compte que tu as terminés et dont tu as réussi le test, et il est délivré avec la signature du Dr. Daniel Wallerstorfer.",
 "cert_cta_name_label": "Nom sur le certificat",
 "cert_cta_name_placeholder": "p. ex. Marie Dupont",
 "cert_cta_generate": "Générer le certificat →",
 "cert_cta_sample": "Voir l'exemple",
 "cert_cta_empty_hint": "Tu n'as encore certifié aucun cours. Jette un œil au certificat exemple.",
 "cert_cta_name_placeholder_seal": "Ton nom ici",
 "cert_mini_presented": "Ce certificat confirme que",
 "cert_mini_genetik_coach": "GENETICS COACH",
 "cl_back": "Retour à l'académie",
 "cl_tag_course": "Cours",
 "cl_tag_training": "Formation",
 "cl_tag_faq": "Recueil de FAQ",
 "cl_tag_supplementary": "Matériel complémentaire",
 "cl_certifiable_yes": "Certifiable — réussis le test et ce module est ajouté à ton certificat.",
 "cl_certifiable_no": "Matériel complémentaire uniquement — non répertorié sur le certificat.",
 "cl_certified_done": "✓ Tu as déjà terminé ce module avec certification.",
 "cl_bullets_h_prefix": "Ce que ce ",
 "cl_bullets_h_suffix": " t'apprend",
 "cl_start_course": "Commencer le cours",
 "cl_start_training": "Commencer la formation",
 "cl_open_faq": "Ouvrir le recueil de FAQ",
 "cl_open_material": "Ouvrir le matériel complémentaire",
 "cl_review": "Revoir le module",
 "cc_back": "Retour à l'aperçu",
 "cc_video_optional": "Visionnage optionnel — l'ordre n'est pas imposé.",
 "cc_complete_module": "Terminer le module",
 "cc_complete_module_sub": "Marque le module comme visionné.",
 "cc_start_test": "Commencer le test",
 "cc_start_test_sub": "Prouve tes connaissances et obtiens ton certificat",
 "cc_videos_h": "Leçon",
 "cc_materials_h": "Matériels & Téléchargements",
 "cc_articles_h": "Matériel de lecture",
 "cc_faq_h": "Questions fréquentes",
 "test_title_prefix": "Test :",
 "test_q_label": "Question",
 "test_back": "Retour au cours",
 "test_submit_a": "Terminer le test (",
 "test_submit_b": " répondues)",
 "test_intro": "Réponds à toutes les questions et termine le module avec tes connaissances.",
 "test_result_pass_title": "Réussi ! 🎉",
 "test_result_fail_title": "Non réussi",
 "test_score_label": "Ton score :",
 "test_pass_threshold": "Au moins 70 % pour réussir.",
 "test_retry": "Réessayer",
 "test_review_course": "Revoir le cours",
 "test_back_home": "Retour à l'académie",
 "certpage_back": "Retour",
 "certpage_download": "Télécharger le PDF",
 "certpage_print": "Imprimer",
 "certpage_completed_on": "Le",
 "certpage_completed_suffix": " a terminé et réussi avec succès les modules de formation suivants :",
 "certpage_presented_to": "Ce certificat confirme que",
 "brand_notice_title": "IMPORTANT À SAVOIR",
 "brand_notice_text": "Les programmes d'analyse existent sous différentes marques et dans différentes versions ; il se peut donc que les designs et les couvertures des rapports présentés dans les supports ne correspondent pas exactement à tes propres designs. Ces formations restent toutefois valables pour toutes les marques.",
 "misc_loading": "Chargement…",
 "misc_other": "Autre",
 "langpick_title": "Choisis ta langue",
 "langpick_sub": "Tu pourras modifier ce choix à tout moment par la suite.",
 "brand_coach": "Genetics Coach",
 "landing_hero_title": "Deviens Genetics Coach",
 "landing_hero_sub": "La plateforme de formation officielle de Novogenia. Apprends à ton rythme, termine les modules avec des tests et obtiens ton certificat officiel de Novogenia Genetics Coach.",
 "landing_cta_signup": "Commencer gratuitement",
 "landing_cta_login": "Déjà inscrit ? Connecte-toi",
 "landing_feature_videos_t": "22 cours en ligne",
 "landing_feature_videos_d": "Enseignés par le Dr. Daniel Wallerstorfer en personne — science, conseil et FAQ couvrant chaque analyse Novogenia.",
 "landing_feature_certs_t": "Un vrai certificat",
 "landing_feature_certs_d": "Réussis les tests des modules et télécharge ton certificat Genetics Coach personnalisé au format PDF.",
 "landing_feature_progress_t": "Progression sur tous les appareils",
 "landing_feature_progress_d": "Ta progression est enregistrée sur ton compte — disponible partout, sur tous tes appareils.",
 "landing_feature_pace_t": "À ton propre rythme",
 "landing_feature_pace_d": "Commence quand tu veux, mets en pause, continue. Pas de stress, pas de délais.",
 "landing_who_title": "À qui s'adresse l'académie ?",
 "landing_who_resellers": "Partenaires et revendeurs qui proposent les analyses Novogenia et souhaitent conseiller leurs clients en toute confiance.",
 "landing_who_pros": "Nutritionnistes, coachs, pharmaciens et médecins qui souhaitent ajouter une dimension génétique à leur pratique.",
 "landing_who_curious": "Toute personne qui souhaite comprendre comment les gènes façonnent notre santé, notre alimentation, nos performances et notre beauté.",
 "auth_signup_title": "Crée ton compte",
 "auth_login_title": "Connexion",
 "auth_signup_sub": "Email et mot de passe — c'est tout. Tu es prêt en 10 secondes.",
 "auth_login_sub": "Bon retour. Reprends là où tu t'es arrêté.",
 "auth_email_label": "Email",
 "auth_email_placeholder": "toi@email.com",
 "auth_password_label": "Mot de passe",
 "auth_password_placeholder": "Au moins 8 caractères",
 "auth_name_label": "Ton nom",
 "auth_name_placeholder": "p. ex. Marie Dupont",
 "auth_name_hint": "Apparaîtra sur ton certificat.",
 "auth_submit_signup": "Créer le compte →",
 "auth_submit_login": "Se connecter →",
 "auth_or_continue_with": "ou continuer avec",
 "auth_google": "Continuer avec Google",
 "auth_switch_to_login": "Déjà inscrit ? Connecte-toi",
 "auth_switch_to_signup": "Nouveau ici ? Crée un compte",
 "auth_error_invalid": "Email ou mot de passe invalide.",
 "auth_error_taken": "Cet email est déjà enregistré. Connecte-toi.",
 "auth_error_weak": "Mot de passe trop court (au moins 8 caractères).",
 "auth_loading": "Veuillez patienter…",
 "user_signed_in_as": "Connecté en tant que",
 "user_logout": "Se déconnecter",
 "admin_title": "Admin",
 "admin_back": "← Retour à l'académie",
 "admin_tab_dashboard": "Tableau de bord",
 "admin_tab_users": "Utilisateurs",
 "admin_stat_total_users": "Utilisateurs au total",
 "admin_stat_new_7d": "Nouveaux sur 7 jours",
 "admin_stat_new_30d": "Nouveaux sur 30 jours",
 "admin_stat_active": "Actifs (≥1 cours visionné)",
 "admin_stat_certified": "Avec certificat",
 "admin_stat_total_progress": "Total des cours terminés",
 "admin_stat_lang_split": "Répartition des langues",
 "admin_stat_growth": "Croissance des utilisateurs (30 jours)",
 "admin_users_search": "Rechercher par email ou nom…",
 "admin_users_col_user": "Utilisateur",
 "admin_users_col_signup": "Inscrit le",
 "admin_users_col_lang": "Langue",
 "admin_users_col_progress": "Progression",
 "admin_users_col_actions": "Actions",
 "admin_user_admin_badge": "ADMIN",
 "admin_user_expand": "Afficher les cours",
 "admin_user_collapse": "Réduire",
 "admin_course_state_done": "Terminé",
 "admin_course_state_partial": "Seulement visionné",
 "admin_course_state_open": "Ouvert",
 "admin_course_set_done": "Marquer comme terminé",
 "admin_course_reset": "Réinitialiser à ouvert",
 "admin_loading": "Chargement des données utilisateurs…",
 "admin_no_users": "Aucun utilisateur trouvé.",
 "admin_no_matches": "Aucun résultat pour la recherche.",
 "admin_action_promote": "Promouvoir admin",
 "admin_action_demote": "Retirer les droits admin",
 "admin_action_rename": "Renommer",
 "admin_action_rename_prompt": "Nouveau nom :",
 "admin_action_reset_all": "Réinitialiser toute la progression",
 "admin_action_reset_confirm": "Vraiment effacer TOUTE la progression des cours de cet utilisateur ?",
 "admin_action_delete": "Supprimer l'utilisateur",
 "admin_action_delete_confirm": "Vraiment supprimer cet utilisateur ?\n\nLe compte lui-même reste, mais disparaît de la liste admin et toute la progression des cours est supprimée.",
 "admin_show_deleted": "Afficher les supprimés",
 "cookie_title": "Cookies & Confidentialité",
 "cookie_text": "Nous utilisons des cookies nécessaires pour l'espace de connexion. Les vidéos YouTube intégrées chargent des cookies supplémentaires de Google — nous te demandons ton consentement pour ceux-ci.",
 "cookie_accept_all": "Tout accepter",
 "cookie_necessary": "Nécessaires uniquement",
 "cookie_privacy_link": "Politique de confidentialité",
 "cookie_yt_blocked": "Charger la vidéo",
 "cookie_yt_blocked_hint": "Nécessite les cookies YouTube. Merci de donner ton consentement.",
 "cookie_yt_allow": "Donner mon consentement",
 "cookie_settings": "Paramètres des cookies",
 "cookie_revoke": "Révoquer le consentement",
 "footer_impressum": "Mentions légales",
 "footer_datenschutz": "Confidentialité",
 "footer_back": "← Retour",
 "impressum_title": "Mentions légales",
 "impressum_operator": "Exploitant",
 "impressum_managing": "Gérant",
 "impressum_register": "Registre du commerce",
 "impressum_uidde": "N° de TVA",
 "impressum_authority": "Autorité de surveillance",
 "impressum_applicable_law": "Réglementations applicables",
 "impressum_contact": "Contact",
 "impressum_liability": "Avis de responsabilité",
 "impressum_liability_text": "Malgré un contrôle minutieux du contenu, nous déclinons toute responsabilité quant au contenu des liens externes. Les exploitants des pages liées sont seuls responsables de leur contenu.",
 "datenschutz_title": "Politique de confidentialité"
},
  pt: {
 "home_courses_section_title": "OS TEUS CURSOS ONLINE",
 "home_courses_section_sub": "Escolhe um módulo entre os temas abaixo e começa o teu treino.",
 "home_progress_of": "de",
 "home_progress_label": "módulos disponíveis concluídos",
 "cert_cta_title": "Gera o teu certificado",
 "cert_cta_intro_a": "Confirma o teu progresso de aprendizagem com o certificado oficial ",
 "cert_cta_intro_b": ". Inclui todos os ",
 "cert_cta_intro_c": " módulos da tua conta que concluíste e cujos testes passaste, e é emitido com a assinatura do Dr. Daniel Wallerstorfer.",
 "cert_cta_name_label": "Nome no certificado",
 "cert_cta_name_placeholder": "p. ex. Maria Silva",
 "cert_cta_generate": "Gerar certificado →",
 "cert_cta_sample": "Ver exemplo",
 "cert_cta_empty_hint": "Ainda não certificaste nenhum curso. Dá uma vista de olhos ao certificado de exemplo.",
 "cert_cta_name_placeholder_seal": "O teu nome aqui",
 "cert_mini_presented": "Este certificado confirma que",
 "cert_mini_genetik_coach": "GENETICS COACH",
 "cl_back": "Voltar à academia",
 "cl_tag_course": "Curso",
 "cl_tag_training": "Formação",
 "cl_tag_faq": "Coletânea de FAQ",
 "cl_tag_supplementary": "Material complementar",
 "cl_certifiable_yes": "Certificável — passa o teste e este módulo é adicionado ao teu certificado.",
 "cl_certifiable_no": "Apenas material complementar — não consta do certificado.",
 "cl_certified_done": "✓ Já concluíste este módulo com certificação.",
 "cl_bullets_h_prefix": "O que este ",
 "cl_bullets_h_suffix": " te ensina",
 "cl_start_course": "Iniciar o curso",
 "cl_start_training": "Iniciar a formação",
 "cl_open_faq": "Abrir a coletânea de FAQ",
 "cl_open_material": "Abrir o material complementar",
 "cl_review": "Rever o módulo novamente",
 "cc_back": "Voltar à visão geral",
 "cc_video_optional": "Visualização opcional — a ordem não é obrigatória.",
 "cc_complete_module": "Concluir o módulo",
 "cc_complete_module_sub": "Marca o módulo como visto.",
 "cc_start_test": "Iniciar o teste",
 "cc_start_test_sub": "Demonstra os teus conhecimentos e garante o teu certificado",
 "cc_videos_h": "Lição",
 "cc_materials_h": "Materiais & Transferências",
 "cc_articles_h": "Material de leitura",
 "cc_faq_h": "Perguntas frequentes",
 "test_title_prefix": "Teste:",
 "test_q_label": "Pergunta",
 "test_back": "Voltar ao curso",
 "test_submit_a": "Concluir o teste (",
 "test_submit_b": " respondidas)",
 "test_intro": "Responde a todas as perguntas e conclui o módulo com os teus conhecimentos.",
 "test_result_pass_title": "Aprovado! 🎉",
 "test_result_fail_title": "Não aprovado",
 "test_score_label": "A tua pontuação:",
 "test_pass_threshold": "Pelo menos 70 % para passar.",
 "test_retry": "Tentar novamente",
 "test_review_course": "Rever o curso novamente",
 "test_back_home": "Voltar à academia",
 "certpage_back": "Voltar",
 "certpage_download": "Transferir PDF",
 "certpage_print": "Imprimir",
 "certpage_completed_on": "Em",
 "certpage_completed_suffix": " concluiu e passou com sucesso os seguintes módulos de formação:",
 "certpage_presented_to": "Este certificado confirma que",
 "brand_notice_title": "IMPORTANTE SABER",
 "brand_notice_text": "Os programas de análise existem sob várias marcas e em diferentes versões, pelo que os designs e as capas dos relatórios apresentados nos materiais podem não corresponder exatamente aos teus próprios designs. No entanto, estas formações continuam válidas para todas as marcas.",
 "misc_loading": "A carregar…",
 "misc_other": "Outros",
 "langpick_title": "Escolhe o teu idioma",
 "langpick_sub": "Podes alterar esta escolha a qualquer momento mais tarde.",
 "brand_coach": "Genetics Coach",
 "landing_hero_title": "Torna-te Genetics Coach",
 "landing_hero_sub": "A plataforma de formação oficial da Novogenia. Aprende ao teu ritmo, conclui módulos com testes e obtém o teu certificado oficial de Novogenia Genetics Coach.",
 "landing_cta_signup": "Começar gratuitamente",
 "landing_cta_login": "Já estás registado? Inicia sessão",
 "landing_feature_videos_t": "22 cursos online",
 "landing_feature_videos_d": "Ensinados pelo próprio Dr. Daniel Wallerstorfer — ciência, aconselhamento e FAQ sobre todas as análises da Novogenia.",
 "landing_feature_certs_t": "Certificado verdadeiro",
 "landing_feature_certs_d": "Passa os testes dos módulos e transfere o teu certificado personalizado de Genetics Coach em PDF.",
 "landing_feature_progress_t": "Progresso em todos os dispositivos",
 "landing_feature_progress_d": "O teu progresso é guardado na tua conta — disponível em todo o lado, em todos os dispositivos.",
 "landing_feature_pace_t": "Ao teu próprio ritmo",
 "landing_feature_pace_d": "Começa quando quiseres, faz uma pausa, continua. Sem stress, sem prazos.",
 "landing_who_title": "A quem se destina a academia?",
 "landing_who_resellers": "Parceiros e revendedores que oferecem as análises da Novogenia e querem aconselhar os seus clientes com confiança.",
 "landing_who_pros": "Nutricionistas, coaches, farmacêuticos e médicos que querem acrescentar uma dimensão genética à sua prática.",
 "landing_who_curious": "Todos os que querem perceber como os genes moldam a nossa saúde, alimentação, desempenho e beleza.",
 "auth_signup_title": "Cria a tua conta",
 "auth_login_title": "Iniciar sessão",
 "auth_signup_sub": "Email e palavra-passe — pronto. Estás dentro em 10 segundos.",
 "auth_login_sub": "Bem-vindo de volta. Continua de onde paraste.",
 "auth_email_label": "Email",
 "auth_email_placeholder": "tu@email.com",
 "auth_password_label": "Palavra-passe",
 "auth_password_placeholder": "Pelo menos 8 caracteres",
 "auth_name_label": "O teu nome",
 "auth_name_placeholder": "p. ex. Maria Silva",
 "auth_name_hint": "Será apresentado no teu certificado.",
 "auth_submit_signup": "Criar conta →",
 "auth_submit_login": "Iniciar sessão →",
 "auth_or_continue_with": "ou continuar com",
 "auth_google": "Continuar com o Google",
 "auth_switch_to_login": "Já estás registado? Inicia sessão",
 "auth_switch_to_signup": "Novo por aqui? Cria uma conta",
 "auth_error_invalid": "Email ou palavra-passe inválidos.",
 "auth_error_taken": "Este email já está registado. Por favor, inicia sessão.",
 "auth_error_weak": "Palavra-passe demasiado curta (pelo menos 8 caracteres).",
 "auth_loading": "Por favor, aguarda…",
 "user_signed_in_as": "Sessão iniciada como",
 "user_logout": "Terminar sessão",
 "admin_title": "Admin",
 "admin_back": "← Voltar à academia",
 "admin_tab_dashboard": "Painel",
 "admin_tab_users": "Utilizadores",
 "admin_stat_total_users": "Total de utilizadores",
 "admin_stat_new_7d": "Novos nos últimos 7 dias",
 "admin_stat_new_30d": "Novos nos últimos 30 dias",
 "admin_stat_active": "Ativos (≥1 curso visto)",
 "admin_stat_certified": "Com certificado",
 "admin_stat_total_progress": "Total de cursos concluídos",
 "admin_stat_lang_split": "Distribuição por idioma",
 "admin_stat_growth": "Crescimento de utilizadores (30 dias)",
 "admin_users_search": "Procurar por email ou nome…",
 "admin_users_col_user": "Utilizador",
 "admin_users_col_signup": "Registado em",
 "admin_users_col_lang": "Idioma",
 "admin_users_col_progress": "Progresso",
 "admin_users_col_actions": "Ações",
 "admin_user_admin_badge": "ADMIN",
 "admin_user_expand": "Mostrar cursos",
 "admin_user_collapse": "Recolher",
 "admin_course_state_done": "Concluído",
 "admin_course_state_partial": "Apenas visto",
 "admin_course_state_open": "Aberto",
 "admin_course_set_done": "Marcar como concluído",
 "admin_course_reset": "Repor como aberto",
 "admin_loading": "A carregar dados dos utilizadores…",
 "admin_no_users": "Nenhum utilizador encontrado.",
 "admin_no_matches": "Nenhum resultado para a pesquisa.",
 "admin_action_promote": "Promover a admin",
 "admin_action_demote": "Remover direitos de admin",
 "admin_action_rename": "Mudar o nome",
 "admin_action_rename_prompt": "Novo nome:",
 "admin_action_reset_all": "Repor todo o progresso",
 "admin_action_reset_confirm": "Apagar mesmo TODO o progresso dos cursos deste utilizador?",
 "admin_action_delete": "Eliminar utilizador",
 "admin_action_delete_confirm": "Eliminar mesmo este utilizador?\n\nA conta em si permanece, mas desaparece da lista de admin e todo o progresso dos cursos é eliminado.",
 "admin_show_deleted": "Mostrar eliminados",
 "cookie_title": "Cookies & Privacidade",
 "cookie_text": "Utilizamos cookies necessários para a área de início de sessão. Os vídeos do YouTube incorporados carregam cookies adicionais da Google — pedimos o teu consentimento para estes.",
 "cookie_accept_all": "Aceitar todos",
 "cookie_necessary": "Apenas os necessários",
 "cookie_privacy_link": "Política de Privacidade",
 "cookie_yt_blocked": "Carregar vídeo",
 "cookie_yt_blocked_hint": "Requer cookies do YouTube. Por favor, dá o teu consentimento.",
 "cookie_yt_allow": "Dar consentimento",
 "cookie_settings": "Definições de cookies",
 "cookie_revoke": "Revogar consentimento",
 "footer_impressum": "Informação legal",
 "footer_datenschutz": "Privacidade",
 "footer_back": "← Voltar",
 "impressum_title": "Informação legal",
 "impressum_operator": "Operador",
 "impressum_managing": "Diretor-geral",
 "impressum_register": "Registo comercial",
 "impressum_uidde": "NIF",
 "impressum_authority": "Autoridade de supervisão",
 "impressum_applicable_law": "Regulamentos aplicáveis",
 "impressum_contact": "Contacto",
 "impressum_liability": "Aviso de responsabilidade",
 "impressum_liability_text": "Apesar do controlo cuidadoso dos conteúdos, não assumimos qualquer responsabilidade pelo conteúdo de ligações externas. Os operadores das páginas ligadas são os únicos responsáveis pelo respetivo conteúdo.",
 "datenschutz_title": "Política de Privacidade"
},
  nl: {
   "home_courses_section_title": "JOUW ONLINECURSUSSEN",
   "home_courses_section_sub": "Kies een module uit de thema's hieronder en begin aan jouw traject.",
   "home_progress_of": "van",
   "home_progress_label": "beschikbare modules voltooid",
   "cert_cta_title": "Genereer jouw certificaat",
   "cert_cta_intro_a": "Bevestig je leervoortgang met het officiële certificaat ",
   "cert_cta_intro_b": ". Het bevat alle ",
   "cert_cta_intro_c": " modules van jouw account die je hebt voltooid en waarvan je de test hebt gehaald, en wordt uitgereikt met de handtekening van Dr. Daniel Wallerstorfer.",
   "cert_cta_name_label": "Naam op het certificaat",
   "cert_cta_name_placeholder": "bijv. Anna Jansen",
   "cert_cta_generate": "Genereer certificaat →",
   "cert_cta_sample": "Bekijk voorbeeld",
   "cert_cta_empty_hint": "Je hebt nog geen enkele cursus gecertificeerd. Bekijk het voorbeeldcertificaat.",
   "cert_cta_name_placeholder_seal": "Jouw naam hier",
   "cert_mini_presented": "Dit certificaat bevestigt dat",
   "cert_mini_genetik_coach": "GENETIK COACH",
   "cl_back": "Terug naar de academie",
   "cl_tag_course": "Cursus",
   "cl_tag_training": "Training",
   "cl_tag_faq": "FAQ-verzameling",
   "cl_tag_supplementary": "Aanvullend materiaal",
   "cl_certifiable_yes": "Certificeerbaar — haal de test en deze module wordt toegevoegd aan jouw certificaat.",
   "cl_certifiable_no": "Alleen aanvullend materiaal — komt niet op het certificaat.",
   "cl_certified_done": "✓ Je hebt deze module al voltooid met certificering.",
   "cl_bullets_h_prefix": "Wat leert deze ",
   "cl_bullets_h_suffix": " je",
   "cl_start_course": "Begin de cursus",
   "cl_start_training": "Begin de training",
   "cl_open_faq": "Open de FAQ-verzameling",
   "cl_open_material": "Open het aanvullende materiaal",
   "cl_review": "Bekijk de module opnieuw",
   "cc_back": "Terug naar het overzicht",
   "cc_video_optional": "Bekijken is optioneel — de volgorde is niet bindend.",
   "cc_complete_module": "Voltooi de module",
   "cc_complete_module_sub": "Markeer de module als bekeken.",
   "cc_start_test": "Begin de test",
   "cc_start_test_sub": "Test je kennis en behaal je certificaat",
   "cc_videos_h": "Les",
   "cc_materials_h": "Materialen en downloads",
   "cc_articles_h": "Leesmateriaal",
   "cc_faq_h": "Veelgestelde vragen",
   "test_title_prefix": "Test:",
   "test_q_label": "Vraag",
   "test_back": "Terug naar de cursus",
   "test_submit_a": "Beëindig de test (",
   "test_submit_b": " antwoorden)",
   "test_intro": "Beantwoord alle vragen en voltooi de module met jouw kennis.",
   "test_result_pass_title": "Geslaagd! 🎉",
   "test_result_fail_title": "Niet geslaagd",
   "test_score_label": "Jouw score:",
   "test_pass_threshold": "Minstens 70% om te slagen voor de test.",
   "test_retry": "Opnieuw proberen",
   "test_review_course": "Bekijk de cursus opnieuw",
   "test_back_home": "Terug naar de academie",
   "certpage_back": "Terug",
   "certpage_download": "Download pdf",
   "certpage_print": "Afdrukken",
   "certpage_completed_on": "Op",
   "certpage_completed_suffix": " heeft de volgende opleidingsmodules met succes voltooid en gehaald:",
   "certpage_presented_to": "Dit certificaat bevestigt dat",
   "brand_notice_title": "BELANGRIJK OM TE WETEN",
   "brand_notice_text": "De analyseprogramma's zijn verkrijgbaar onder verschillende merken en in diverse versies, dus de ontwerpen en covers van de rapporten in het materiaal komen mogelijk niet exact overeen met die van jou. Deze opleidingen blijven hoe dan ook geldig voor alle merken.",
   "misc_loading": "Bezig met laden…",
   "misc_other": "Overig",
   "langpick_title": "Kies jouw taal",
   "langpick_sub": "Je kunt deze keuze op elk moment wijzigen.",
   "brand_coach": "Genetik Coach",
   "landing_hero_title": "Word Genetik Coach",
   "landing_hero_sub": "Het officiële opleidingsplatform van Novogenia. Leer in jouw eigen tempo, voltooi de modules met de tests en behaal jouw officiële certificaat als Novogenia Genetik Coach.",
   "landing_cta_signup": "Begin gratis",
   "landing_cta_login": "Al geregistreerd? Log in",
   "landing_feature_videos_t": "22 onlinecursussen",
   "landing_feature_videos_d": "Persoonlijk gegeven door Dr. Daniel Wallerstorfer — wetenschap, advies en FAQ over alle Novogenia-analyses.",
   "landing_feature_certs_t": "Echt certificaat",
   "landing_feature_certs_d": "Haal de moduletests en download jouw gepersonaliseerde Genetik Coach-certificaat als pdf.",
   "landing_feature_progress_t": "Overal je voortgang",
   "landing_feature_progress_d": "Jouw voortgang wordt op je account opgeslagen — overal beschikbaar, op elk apparaat.",
   "landing_feature_pace_t": "In jouw eigen tempo",
   "landing_feature_pace_d": "Begin wanneer je wilt, pauzeer, ga verder. Zonder stress, zonder deadlines.",
   "landing_who_title": "Voor wie is de academie bedoeld?",
   "landing_who_resellers": "Partners en wederverkopers die de Novogenia-analyses aanbieden en hun klanten met vertrouwen willen adviseren.",
   "landing_who_pros": "Voedingsdeskundigen, coaches, apothekers en artsen die een genetische dimensie aan hun werk willen toevoegen.",
   "landing_who_curious": "Iedereen die wil begrijpen hoe genen onze gezondheid, voeding, prestaties en schoonheid beïnvloeden.",
   "auth_signup_title": "Maak jouw account aan",
   "auth_login_title": "Log in",
   "auth_signup_sub": "E-mail en wachtwoord — meer niet. Binnen 10 seconden ben je binnen.",
   "auth_login_sub": "Welkom terug. Ga verder waar je gebleven was.",
   "auth_email_label": "E-mail",
   "auth_email_placeholder": "jij@email.com",
   "auth_password_label": "Wachtwoord",
   "auth_password_placeholder": "Minstens 8 tekens",
   "auth_name_label": "Jouw naam",
   "auth_name_placeholder": "bijv. Anna Jansen",
   "auth_name_hint": "Deze verschijnt op jouw certificaat.",
   "auth_submit_signup": "Account aanmaken →",
   "auth_submit_login": "Log in →",
   "auth_or_continue_with": "of ga verder met",
   "auth_google": "Ga verder met Google",
   "auth_switch_to_login": "Al geregistreerd? Log in",
   "auth_switch_to_signup": "Nieuw hier? Maak een account aan",
   "auth_error_invalid": "E-mail of wachtwoord ongeldig.",
   "auth_error_taken": "Dit e-mailadres is al geregistreerd. Log in plaats daarvan in.",
   "auth_error_weak": "Wachtwoord te kort (minstens 8 tekens).",
   "auth_loading": "Even geduld…",
   "user_signed_in_as": "Ingelogd als",
   "user_logout": "Uitloggen",
   "admin_title": "Admin",
   "admin_back": "← Terug naar de academie",
   "admin_tab_dashboard": "Dashboard",
   "admin_tab_users": "Gebruikers",
   "admin_stat_total_users": "Totaal aantal gebruikers",
   "admin_stat_new_7d": "Nieuw in de afgelopen 7 dagen",
   "admin_stat_new_30d": "Nieuw in de afgelopen 30 dagen",
   "admin_stat_active": "Actief (≥1 cursus bekeken)",
   "admin_stat_certified": "Met certificaat",
   "admin_stat_total_progress": "Totaal aantal voltooide cursussen",
   "admin_stat_lang_split": "Verdeling per taal",
   "admin_stat_growth": "Gebruikersgroei (30 dagen)",
   "admin_users_search": "Zoek op e-mail of naam…",
   "admin_users_col_user": "Gebruiker",
   "admin_users_col_signup": "Geregistreerd",
   "admin_users_col_lang": "Taal",
   "admin_users_col_progress": "Voortgang",
   "admin_users_col_actions": "Acties",
   "admin_user_admin_badge": "ADMIN",
   "admin_user_expand": "Toon cursussen",
   "admin_user_collapse": "Inklappen",
   "admin_course_state_done": "Voltooid",
   "admin_course_state_partial": "Alleen bekeken",
   "admin_course_state_open": "Open",
   "admin_course_set_done": "Markeer als voltooid",
   "admin_course_reset": "Terugzetten op open",
   "admin_loading": "Gebruikersgegevens laden…",
   "admin_no_users": "Geen gebruikers gevonden.",
   "admin_no_matches": "Geen resultaten voor de zoekopdracht.",
   "admin_action_promote": "Promoveer tot admin",
   "admin_action_demote": "Verwijder adminrechten",
   "admin_action_rename": "Hernoem",
   "admin_action_rename_prompt": "Nieuwe naam:",
   "admin_action_reset_all": "Reset alle voortgang",
   "admin_action_reset_confirm": "Wil je echt ALLE cursusvoortgang van deze gebruiker wissen?",
   "admin_action_delete": "Verwijder gebruiker",
   "admin_action_delete_confirm": "Wil je deze gebruiker echt verwijderen?\n\nHet account blijft actief, maar verdwijnt uit de adminlijst en alle cursusvoortgang wordt verwijderd.",
   "admin_show_deleted": "Toon verwijderde",
   "cookie_title": "Cookies en privacy",
   "cookie_text": "We gebruiken de cookies die nodig zijn voor het inloggedeelte. Ingesloten YouTube-video's laden extra cookies van Google — daarvoor vragen we jouw toestemming.",
   "cookie_accept_all": "Alles accepteren",
   "cookie_necessary": "Alleen noodzakelijke",
   "cookie_privacy_link": "Privacyverklaring",
   "cookie_yt_blocked": "Video laden",
   "cookie_yt_blocked_hint": "Vereist YouTube-cookies. Geef je toestemming.",
   "cookie_yt_allow": "Geef toestemming",
   "cookie_settings": "Cookie-instellingen",
   "cookie_revoke": "Toestemming intrekken",
   "footer_impressum": "Juridische informatie",
   "footer_datenschutz": "Privacy",
   "footer_back": "← Terug",
   "impressum_title": "Juridische informatie",
   "impressum_operator": "Beheerder",
   "impressum_managing": "Directeur",
   "impressum_register": "Handelsregister",
   "impressum_uidde": "Btw-nummer",
   "impressum_authority": "Toezichthoudende instantie",
   "impressum_applicable_law": "Toepasselijke regelgeving",
   "impressum_contact": "Contact",
   "impressum_liability": "Aansprakelijkheidsverklaring",
   "impressum_liability_text": "Ondanks een zorgvuldige controle van de inhoud aanvaarden wij geen aansprakelijkheid voor de inhoud van externe links. De beheerders van de gelinkte pagina's zijn als enige verantwoordelijk voor hun inhoud.",
   "datenschutz_title": "Privacyverklaring",
  },
}
